imageprocessing/urls.py
from django.urls import path

from . import views

app_name = 'imageprocessing'
urlpatterns = [
    path('', views.classification, name='glasses'),
    path('Frederick/', views.fred, name='fred'),
    path('Johannes/', views.johannes, name='johannes'),
    path('Jimothy/', views.jimothy, name='jimothy'),
    path('Lana/', views.lana, name='lana'),
    ]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'homepage'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('imageprocessing.urls')),
    #path('', views.home)
]

imageprocessing/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

imageprocessing/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.conf import settings
base_dir = settings.BASE_DIR

from .models import Choice, Question
from .testKNN import knn


class IndexView(generic.ListView):
    template_name = 'imageprocessing/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'imageprocessing/Fred.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'imageprocessing/results.html'


def classification(request):
    return render(request, 'imageprocessing/glasses/indexdetail.html')

def fred(request):
    context = {}
    if request.GET:
        numneighbors = request.GET['numneighbors']
        # get return values
        context = knn(name=1, neighbors=numneighbors, dir=base_dir)
        print(context)
    return render(request, 'imageprocessing/glasses/Fred.html', {'context': context})

def johannes(request):
    context = {}
    if request.GET:
        numneighbors = request.GET['numneighbors']
        # get return values
        context = knn(name=2, neighbors=numneighbors, dir=base_dir)
        print(context)
    return render(request, 'imageprocessing/glasses/Johannes.html', {'context': context})

def jimothy(request):
    context = {}
    if request.GET:
        numneighbors = request.GET['numneighbors']
        # get return values
        context = knn(name=3, neighbors=numneighbors, dir=base_dir)
        print(context)
    return render(request, 'imageprocessing/glasses/Jimothy.html', {'context': context})

def lana(request):
    context = {}
    if request.GET:
        numneighbors = request.GET['numneighbors']
        # get return values
        context = knn(name=4, neighbors=numneighbors, dir=base_dir)
        print(context)
    return render(request, 'imageprocessing/glasses/Lana.html', {'context': context})

mysite/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic

app_name = 'homepage'

def home(request):
    return render(request, 'homepage/homepage.html')

imageprocessing/templates/homepage/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}EGR 190L{% endblock %}</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'homestyle.css' %}">

</head>
<body>
    <p>HELLO</p>
    <nav class="navbar navbar-light" style="background-color: #e3f2fd;">
    <div class="container-field">
        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar" style="background-color: #000000;"></span>
                <span class="icon-bar" style="background-color: #000000;"></span>
                <span class="icon-bar" style="background-color: #000000;"></span>

            </button>
            <a class="navbar-brand" href="/">EGR 190L</a>
        </div>

        <!-- Items -->
        <!--<div class="collapse navbar-collapse" id="topNavBar">-->
            <!--<ul class="nav navbar-nav">-->

                <!--<li class="">-->
                    <!--<a href="#">-->
                        <!--<span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Albums-->
                    <!--</a>-->
                <!--</li>-->

                <!--<li class="">-->
                    <!--<a href="#">-->
                        <!--<span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp; Songs-->
                    <!--</a>-->
                <!--</li>-->


            <!--</ul>-->

            <!--<form class="navbar-form navbar-left" role="search" method="get" action="#">-->
                <!--<div class="form-group">-->
                    <!--<input type="text" class="form-control" name="q" value="">-->
                <!--</div>-->
                <!--<button type="submit" class="btn btn-default">Search</button>-->
            <!--</form>-->

            <!--<ul class="nav navbar-nav navbar-right">-->
                <!--<li class="">-->
                    <!--<a href="#">-->
                        <!--<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Album-->
                    <!--</a>-->
                <!--</li>-->


            <!--<li class="">-->
                    <!--<a href="#">-->
                        <!--<span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout-->
                    <!--</a>-->
                <!--</li>-->
            <!--</ul>-->

        <!--</div>-->

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

imageprocessing/templates/homepage/homepage.html
<!DOCTYPE html>
<html lang="en">
{% extends "homepage/base.html" %}
<head>
    <meta charset="UTF-8">
    <title>Homepage</title>
</head>
<body>
{% block body %}
    <h1>Welcome to my site!</h1>
    <a href="imageprocessing/">Here is the link to Image Classification Section!</a>
{% endblock %}
</body>
</html>

imageprocessing/templates/imageprocessing/glasses/Fred.html
{% extends 'imageprocessing/glasses/indexdetail.html' %}
{% load staticfiles %}

{% block title %}Glasses{% endblock %}
{% block whichactive1 %}active{% endblock %}
{% block pagecontent %}

        <div class="col-lg-7 col-md-offset-1" style="background:white; border-radius:5%;">

          <div class="card mt-4">
          <div class="text-center"><img class="card-img-top img-fluid" src="{% static 'images/Frederick.png' %}" alt="" style="padding-top:15px; border-radius:5%"></div>            <div class="card-body">
              <h3 class="card-title">Frederick</h3>
              <h4>Age: 39, Place of Residence: Menlo Park, CA</h4>
              <p class="card-text">Man oh man, what a stunner! Frederick is a single ready to mingle who's just itching to be <i>your</i> nearest neighbor.
                Select from down below to alter the model and view an ROC curve + confusion matrix.</i></p>
            </div>
          </div>
          <!-- /.card -->

          <div class="card card-outline-secondary my-4">
            <div class="card-body">
              <form action="">
                <div class="form-group row">
                  <label for="numneighbors" class="col-sm-6 col-form-label">Number of Neighbors</label>
                </div>
                <div class="form-group row">
                  <div class="col-lg-8">
                      <select name="numneighbors" class="form-control" id="numneighbors">
                        <option>1</option><option>2</option><option>3</option><option>4</option><option>5</option>
                        <option>6</option><option>7</option><option>8</option><option>9</option><option>10</option>
                        <option>11</option><option>12</option><option>13</option><option>14</option><option>15</option>
                        <option>16</option><option>17</option><option>18</option><option>19</option><option>20</option>
                      </select>

                  </div>
                  <div class="col-lg-4">
                      <button type="submit" class="btn btn-primary">Go</button>
                  </div>
                </div>
              </form>
            </div>
          </div>
          <!-- /.card -->
          {% if  context  %}
            <div class="card mt-4">
            <img class="card-img-top img-fluid" src="{% static 'graphs/ROC.png' %}" alt="">
            <div class="card-body">
              <h1 class="card-title"><strong>We are {{ context.certainty|stringformat:".2f" }} percent sure that Frederick is wearing glasses using this number of neighbors (based off this single image).</strong></h1>
              <h2 class="card-title">Confusion Matrix: </h2>
              <table class="table table-striped table-dark">
                <thead>
                  <tr>
                    <th scope="col"></th>
                    <th scope="col">Predicted: No Glasses</th>
                    <th scope="col">Predicted: Glasses</th>
                  </tr>
                </thead>
                  <tbody>
                    <tr>
                      <th scope="row">Actual: No Glasses</th>
                      <td>{{ context.cm1 }}</td>
                      <td>{{ context.cm2 }}</td>
                    </tr>
                    <tr>
                      <th scope="row">Actual: Glasses</th>
                      <td>{{ context.cm3 }}</td>
                      <td>{{ context.cm4 }}</td>
                    </tr>
                  </tbody>
              </table>
            </div>
          </div>
          {% endif %}
        </div>
{% endblock %}

imageprocessing/templates/imageprocessing/glasses/Jimothy.html
{% extends 'imageprocessing/glasses/indexdetail.html' %}
{% load staticfiles %}

{% block title %}Glasses{% endblock %}
{% block whichactive3 %}active{% endblock %}
{% block pagecontent %}

        <div class="col-lg-7 col-md-offset-1" style="background:white; border-radius:5%;">

          <div class="card mt-4">
            <div class="text-center"><img class="card-img-top img-fluid" src="{% static 'images/Jimothy.png' %}" alt="" style="padding-top:15px; border-radius:5%"></div>
            <div class="card-body">
              <h3 class="card-title">Jimothy</h3>
              <h4>Age: 18, Place of Residence: Denver, Colorado</h4>
              <p class="card-text">Jimothy is just trying to cast a wide neural net.
                Select from down below to alter the model and view an ROC curve + confusion matrix.</i></p>
            </div>
          </div>
          <!-- /.card -->

          <div class="card card-outline-secondary my-4">
            <div class="card-body">
              <form action="">
                <div class="form-group row">
                  <label for="numneighbors" class="col-sm-6 col-form-label">Number of Neighbors</label>
                </div>
                <div class="form-group row">
                  <div class="col-lg-8">
                      <select name="numneighbors" class="form-control" id="numneighbors">
                        <option>1</option><option>2</option><option>3</option><option>4</option><option>5</option>
                        <option>6</option><option>7</option><option>8</option><option>9</option><option>10</option>
                        <option>11</option><option>12</option><option>13</option><option>14</option><option>15</option>
                        <option>16</option><option>17</option><option>18</option><option>19</option><option>20</option>
                      </select>

                  </div>
                  <div class="col-lg-4">
                      <button type="submit" class="btn btn-primary">Go</button>
                  </div>
                </div>
              </form>
            </div>
          </div>
          <!-- /.card -->
          {% if  context  %}
            <div class="card mt-4">
            <img class="card-img-top img-fluid" src="{% static 'graphs/ROC.png' %}" alt="">
            <div class="card-body">
              <h1 class="card-title"><strong>We are {{ context.certainty|stringformat:".2f" }} percent sure that Jimothy is NOT wearing glasses using this number of neighbors (based off this single image).</strong></h1>
              <h2 class="card-title">Confusion Matrix: </h2>
              <table class="table table-striped table-dark">
                <thead>
                  <tr>
                    <th scope="col"></th>
                    <th scope="col">Predicted: No Glasses</th>
                    <th scope="col">Predicted: Glasses</th>
                  </tr>
                </thead>
                  <tbody>
                    <tr>
                      <th scope="row">Actual: No Glasses</th>
                      <td>{{ context.cm1 }}</td>
                      <td>{{ context.cm2 }}</td>
                    </tr>
                    <tr>
                      <th scope="row">Actual: Glasses</th>
                      <td>{{ context.cm3 }}</td>
                      <td>{{ context.cm4 }}</td>
                    </tr>
                  </tbody>
              </table>
            </div>
          </div>
          {% endif %}
        </div>
{% endblock %}

imageprocessing/templates/imageprocessing/glasses/Johannes.html
{% extends 'imageprocessing/glasses/indexdetail.html' %}
{% load staticfiles %}

{% block title %}Glasses{% endblock %}
{% block whichactive2 %}active{% endblock %}
{% block pagecontent %}

        <div class="col-lg-7 col-md-offset-1" style="background:white; border-radius:5%;">

          <div class="card mt-4">
            <div class="text-center"><img class="card-img-top img-fluid" src="{% static 'images/Johannes.png' %}" alt="" style="padding-top:15px; border-radius:5%"></div>
            <div class="card-body">
              <h3 class="card-title">Johannes</h3>
              <h4>Age: 26, Place of Residence: Miami, Florida</h4>
              <p class="card-text">Not to be outdone, Johannes is also looking to meet new people, and pledges to give the right lady the support vector she needs.
                Select from down below to alter the model and view an ROC curve + confusion matrix.</i></p>
            </div>
          </div>
          <!-- /.card -->

          <div class="card card-outline-secondary my-4">
            <div class="card-body">
              <form action="">
                <div class="form-group row">
                  <label for="numneighbors" class="col-sm-6 col-form-label">Number of Neighbors</label>
                </div>
                <div class="form-group row">
                  <div class="col-lg-8">
                      <select name="numneighbors" class="form-control" id="numneighbors">
                        <option>1</option><option>2</option><option>3</option><option>4</option><option>5</option>
                        <option>6</option><option>7</option><option>8</option><option>9</option><option>10</option>
                        <option>11</option><option>12</option><option>13</option><option>14</option><option>15</option>
                        <option>16</option><option>17</option><option>18</option><option>19</option><option>20</option>
                      </select>

                  </div>
                  <div class="col-lg-4">
                      <button type="submit" class="btn btn-primary">Go</button>
                  </div>
                </div>
              </form>
            </div>
          </div>
          <!-- /.card -->
          {% if  context  %}
            <div class="card mt-4">
            <img class="card-img-top img-fluid" src="{% static 'graphs/ROC.png' %}" alt="">
            <div class="card-body">
              <h1 class="card-title"><strong>We are {{ context.certainty|stringformat:".2f" }} percent sure that Johannes is wearing glasses using this number of neighbors (based off this single image).</strong></h1>
              <h2 class="card-title">Confusion Matrix: </h2>
              <table class="table table-striped table-dark">
                <thead>
                  <tr>
                    <th scope="col"></th>
                    <th scope="col">Predicted: No Glasses</th>
                    <th scope="col">Predicted: Glasses</th>
                  </tr>
                </thead>
                  <tbody>
                    <tr>
                      <th scope="row">Actual: No Glasses</th>
                      <td>{{ context.cm1 }}</td>
                      <td>{{ context.cm2 }}</td>
                    </tr>
                    <tr>
                      <th scope="row">Actual: Glasses</th>
                      <td>{{ context.cm3 }}</td>
                      <td>{{ context.cm4 }}</td>
                    </tr>
                  </tbody>
              </table>
            </div>
          </div>
          {% endif %}
        </div>
{% endblock %}

imageprocessing/templates/imageprocessing/glasses/indexdetail.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}EGR 190L{% endblock %}</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static '/homestyle.css' %}">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet" />

</head>
<body>
    <nav class="navbar navbar-inverse">
    <div class="container-field">
        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar" style="background-color: #000000;"></span>
                <span class="icon-bar" style="background-color: #000000;"></span>
                <span class="icon-bar" style="background-color: #000000;"></span>

            </button>
            <a class="navbar-brand" href="/">EGR 190L</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <!--<ul class="nav navbar-nav">-->

                <!--<li class="">-->
                    <!--<a href="#">-->
                        <!--<span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Albums-->
                    <!--</a>-->
                <!--</li>-->

                <!--<li class="">-->
                    <!--<a href="#">-->
                        <!--<span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp; Songs-->
                    <!--</a>-->
                <!--</li>-->


            <!--</ul>-->

            <!--<form class="navbar-form navbar-left" role="search" method="get" action="#">-->
                <!--<div class="form-group">-->
                    <!--<input type="text" class="form-control" name="q" value="">-->
                <!--</div>-->
                <!--<button type="submit" class="btn btn-default">Search</button>-->
            <!--</form>-->

            <ul class="nav navbar-nav navbar-right" style="padding-right:5px">
                <li class="" style="font-family: 'Roboto'">
                    <a href="https://www.linkedin.com/in/feroze-mohideen/">
                        made by Feroze Mohideen
                    </a>
                </li>


            <!--<li class="">-->
                    <!--<a href="#">-->
                        <!--<span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout-->
                    <!--</a>-->
                <!--</li>-->
            </ul>

        </div>

    </div>
</nav>
    <div class="container">

      <div class="row" style="padding:5px">

        <div class="col-md-4" style="background:white; border-radius:5%">
              <h1 class="my-4" style="color:blue;">Who's Got Glasses?</h1>
              <div class="list-group">
                <a href="{% url 'imageprocessing:fred' %}" class="list-group-item {% block whichactive1 %}{% endblock %}">Frederick <span class="glyphicon glyphicon-sunglasses" aria-hidden="true"></span></a>
                <a href="{% url 'imageprocessing:johannes' %}" class="list-group-item {% block whichactive2 %}{% endblock %}" >Johannes <span class="glyphicon glyphicon-sunglasses" aria-hidden="true"></span></a>
                <a href="{% url 'imageprocessing:jimothy' %}" class="list-group-item {% block whichactive3 %}{% endblock %}">Jimothy</a>
                  <a href="{% url 'imageprocessing:lana' %}" class="list-group-item {% block whichactive4 %}{% endblock %}">Lana</a>
              </div>
                <div class="list-group">
                    <a href="/" class="list-group-item">Back to home</a>
                    <a href="https://github.com/ferozemohideen/django-machine-learning" class="list-group-item">Full source code</a>
                </div>
        </div>
        <!-- /.col-lg-3 -->
        {% block pagecontent %}
        <div class="col-lg-7 col-md-offset-1" style="background:white; border-radius:5%;">
                <div class="container-fluid" >
                <h1 style="color:blue">What is KNN?</h1>
                    <p>
                        In pattern recognition, the k-nearest neighbors algorithm (k-NN) is a non-parametric method used for classification and regression. In both cases, the input consists of the k closest training examples in the feature space. The output depends on whether k-NN is used for classification or regression:
                    </p>
                    <ul style="font-size:90%;">
                        <li>
                            In k-NN classification, the output is a class membership. An object is classified by a majority vote of its neighbors, with the object being assigned to the class most common among its k nearest neighbors (k is a positive integer, typically small). If k = 1, then the object is simply assigned to the class of that single nearest neighbor.
                        </li>
                        <li>
                            In k-NN regression, the output is the property value for the object. This value is the average of the values of its k nearest neighbors.
                        </li>
                    </ul>
                    <p>The following image shows this in action: </p>
                    <div class="text-center"><img src="{% static 'images/exampleknn.gif' %}"/></div>
                    <p>
                        In this web app, we explore KNN <i>classification</i> using images, which are innately in a high dimension. If we represent
                        each pixel with a dimension, then each image has over 10,000 dimensions! My goal was to see whether Python could compute
                        nearest neighbors in that high of a dimension efficiently, and as it turned out, it can (although this webapp may take longer time than
                        usual to refresh). In this setting specifically, I wanted to see how well the algorithm could distinguish between images of people wearing
                        glasses, and images of people who aren't - whether there was enough difference between those two groups in the 10,304D feature space. Click
                        on the people on the left and adjust the number of neighbors to see how well the program does! Otherwise, you can read up more on KNN and loads
                        of other fun algorithms in <a href="http://www-bcf.usc.edu/~gareth/ISL/ISLR%20Sixth%20Printing.pdf"><i>An Introduction to Statistical Learning</i> (ISLR)</a>
                        by Gareth James et al. (free online!).
                    </p>
                    <h1 style="color:blue">What is this for?</h1>
                        <p>
                            I took EGR 190: Introduction to Data Science with Dr. Paul Bendich and Dr. Stacy Tantum at Duke Spring 2018 and really loved the statistical learning topics
                            we covered. We pretty much coded exclusively in MATLAB, though, which I think can be kinda clunky sometimes. I got a little <s>bored</s> curious, so I decided to branch off and
                            redo an aspect of this project in Python, and I learned a <i>ton</i> about machine learning (from the textbook linked above) and also web development with Django and
                            styling in HTML with Bootstrap. Click the link on the left for the full source code of the script and this webapp if you want to read more!
                        </p>
                    <h1 style="color:blue">How does it work?</h1>
                        <p>
                            The script uses a training set of 40 men and women, wearing glasses or no glasses. Each person contributed 10 images of themselves
                            shot in different angles, so in reality, there are 400 samples, each with 10,304 features (each image was 112x92). It turns out it's
                            pretty easy to use Sci-Kit Learn in Python to train all sorts of models - the hardest part really was figuring out how to structure the data
                            with Panda dataframes. The people on the left were taken out of the training set, the KNN model was fit and trained, and finally it was
                            used to predict the class of the test subject. <b>One caveat:</b> it's worth mentioning that in the set of people, only a handful of the 40
                            were actually wearing glasses. This would skew the classification in favor of better classifying people without glasses; if I could, I'd
                            choose a more balanced set. Going along with that, in the future I'd also like to test the effects of dimensionality reduction with PCA
                            on the high-dimensional feature space. Performing KNN "upstairs" wasn't too much of an issue - in fact, it led to some perfect classifiers -
                            but it'd be interesting to see what would happen in a lower dimension.
                        </p>
                </div>
        </div>
        {% endblock %}
        <!-- /.col-lg-9 -->
      </div>


    </div>
    <footer class="footer">
        <div class="container" style="justify-content: center;">
            <span class="text-muted">
                This page was made with Python, Django, and Love. Feel free to reach out to me by email at <a href="mailto:fm87@duke.edu">fm87@duke.edu</a> about any suggestions, and please visit my GitHub! :)
            </span> &nbsp;
            <a href="https://github.com/ferozemohideen" class="fa fa-github"></a>
        </div>
    </footer>
</body>

</html>

imageprocessing/templates/imageprocessing/index.html
{% extends 'homepage/base.html' %}
{% block body %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'imageprocessing/style.css' %}" />

<h1>Welcome!!</h1>
<ul>
    <li><a href="{% url 'imageprocessing:glasses' %}">Are They Wearing Glasses?</a></li>
</ul>

{% endblock %}

imageprocessing/templates/imageprocessing/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'imageprocessing:detail' question.id %}">Vote again?</a>